 \
 /Users/lipa/fractalstream/llvm-2.5/tools/llvmc/plugins/Clang/Release/PluginMain.lo \
  /Users/lipa/fractalstream/llvm-2.5/tools/llvmc/plugins/Clang/Release/PluginMain.o \
  /Users/lipa/fractalstream/llvm-2.5/tools/llvmc/plugins/Clang/Release/PluginMain.d \
  /Users/lipa/fractalstream/llvm-2.5/tools/llvmc/plugins/Clang/Release/PluginMain.o:  \
 PluginMain.cpp AutoGenerated.inc \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/CompilationGraph.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Tool.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Action.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/IntrusiveRefCntPtr.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Casting.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringSet.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringMap.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Allocator.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/AlignOf.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/System/Path.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/System/TimeValue.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/GraphTraits.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/iterator.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/SmallVector.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/iterator.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/type_traits.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringMap.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Plugin.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Registry.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Tool.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringExtras.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/APFloat.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/APInt.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/MathExtras.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/CommandLine.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/type_traits.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Compiler.h \
  /Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/SmallVector.h

AutoGenerated.inc:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/CompilationGraph.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Tool.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Action.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/IntrusiveRefCntPtr.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Casting.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringSet.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringMap.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Allocator.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/AlignOf.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/System/Path.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/System/TimeValue.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/GraphTraits.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/iterator.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/SmallVector.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/iterator.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/type_traits.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringMap.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Plugin.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Registry.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/CompilerDriver/Tool.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/StringExtras.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/APFloat.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/APInt.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/MathExtras.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/DataTypes.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/CommandLine.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/type_traits.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/Support/Compiler.h:

/Users/lipa/fractalstream/llvm-2.5/include/llvm/ADT/SmallVector.h:
